---

- hosts: all
  remote_user: host
  become: true
  tasks:

  - name: update repo
    apt:
      update_cache: yes

  - name: Install apache2 pkg
    apt:
      name: apache2

  - name: install php support for apache2
    apt:
      name: libapache2-mod-php
